export const componentDescriptions: Record<string, string> = {
  'pabutton': 'A versatile button component with multiple variants and sizes. Button variants follow a clear hierarchy: Primary (highest priority) → Secondary → Tertiary → Link → Action (lowest priority). Use Primary for the main call-to-action, Secondary for secondary actions, Tertiary for less emphasized actions, and Link for text-style buttons. Supports loading state for async operations.',
  'painput': 'Text input component with validation states, sizes, and icon support.',
  'pacheckbox': 'Checkbox input component with checked, unchecked, and indeterminate states.',
  'paradio': 'Radio button component for single selection in forms.',
  'paradiobuttongroup': 'Group of radio buttons for managing single selection.',
  'paswitch': 'Switch component for boolean inputs.',
  'paselect': 'Dropdown select component with single and multi-select support.',
  'patextarea': 'Multi-line text input component with resize options.',
  'paautocomplete': 'Input component with autocomplete suggestions.',
  'patimepicker': 'Time picker component for selecting time values.',
  'pafileuploader': 'File upload component with drag and drop support.',
  'paform': 'Form wrapper component for managing form state and validation.',
  'pacard': 'Card component for displaying content in a contained format.',
  'paheader': 'Header component for application navigation and branding.',
  'palistitem': 'List item component for displaying items in lists.',
  'papagelayout': 'Page layout component for structuring page content.',
  'pacontentseparator': 'Separator component for dividing content sections.',
  'pacontainer': 'Container component for wrapping and constraining content.',
  'paformcontainer': 'Form container component for grouping form fields.',
  'pasectioncontainer': 'Section container component with title and actions.',
  'padropdown': 'Dropdown menu component with positioning options.',
  'pasegmentedcontrol': 'Segmented control component for selecting between options.',
  'patogglesegmentation': 'Toggle segmentation component for grouped selections.',
  'patogglechip': 'Toggle chip component for tag-like selections.',
  'pakebabmenu': 'Kebab menu component for action menus.',
  'patabs': 'Tabs component for organizing content into panels.',
  'pabreadcrumbs': 'Breadcrumbs component for navigation hierarchy.',
  'pastepper': 'Stepper component for multi-step processes.',
  'padrawer': 'Drawer component for slide-out panels.',
  'pamodal': 'Modal component for dialog overlays.',
  'patooltip': 'Tooltip component for contextual information.',
  'pabadge': 'Badge component for status indicators and labels.',
  'painlinemessage': 'Inline message component for feedback and alerts.',
  'paloading': 'Loading component for indicating progress.',
  'paemptystate': 'Empty state component for when no content is available.',
  'paprogress': 'Progress component for showing completion status.',
  'patable': 'Table component for displaying tabular data.',
  'paaccordion': 'Accordion component for collapsible content sections.',
  'papagination': 'Pagination component for navigating through pages.',
  'paslider': 'Slider component for selecting numeric values.',
  'parangeslider': 'Range slider component for selecting value ranges.',
  'paactionbutton': 'Action button variant wrapper for PaButton.',
  'paactionbuttongroup': 'Group wrapper for multiple action buttons.',
  'paactiongroup': 'Generic action button group component.',
  'pabuttondropdown': 'Button component with dropdown menu functionality.',
  'pacheckboxgroup': 'Group wrapper for multiple checkbox components.',
  'painputgroup': 'Wrapper component for grouped input fields.',
  'pacurrencyinput': 'Specialized input component for currency values.',
  'padatepicker': 'Date selection input component.',
  'paphonenumberinputgroup': 'Specialized input group for phone numbers with country code.',
  'patoggleinputgroup': 'Group of toggle switch inputs.',
  'paoptionalgroup': 'Optional form field group wrapper.',
  'paheroheader': 'Main hero header component for landing pages.',
  'paheroicon': 'Hero icon component for landing pages.',
  'paherosubheader': 'Hero subheader text component.',
  'paherosubheadergroup': 'Group of hero subheader components.',
  'paformdivider': 'Divider component for form sections.',
  'papagedivider': 'Divider component for page sections.',
  'patextcontainer': 'Container component for text content with max-width constraints.',
  'patextdivider': 'Divider component for text sections.',
  'paslottedlayout': 'Layout component with flexible slot system.',
  'paslottedlayoutheader': 'Header component for slotted layout.',
  'pacircle': 'Circular shape component.',
  'pacolorpicker': 'Color selection component using native color input.',
  'padivider': 'Generic divider component for horizontal or vertical separation.',
  'paicon': 'Icon component wrapper for consistent icon sizing and styling.',
  'panavbutton': 'Navigation button component for navigation menus.',
  'panavbuttongroup': 'Group of navigation buttons.',
  'pasheet': 'Sheet/modal-like component that slides in from edges.',
  'pasquare': 'Square shape component.',
  'patoggle': 'Toggle component wrapper for PaSwitch.'
}

export const getComponentDescription = (componentId: string): string => {
  return componentDescriptions[componentId] || 'Component documentation coming soon.'
}

