import {
  PaButton,
  PaInput,
  PaCheckbox,
  PaRadio,
  PaRadioButtonGroup,
  PaSwitch,
  PaSelect,
  PaTextarea,
  PaAutocomplete,
  PaTimePicker,
  PaFileUploader,
  PaForm,
  PaCard,
  PaHeader,
  PaListItem,
  PaPageLayout,
  PaContentSeparator,
  PaContainer,
  PaFormContainer,
  PaSectionContainer,
  PaDropdown,
  PaSegmentedControl,
  PaToggleSegmentation,
  PaToggleChip,
  PaKebabMenu,
  PaTabs,
  PaBreadcrumbs,
  PaStepper,
  PaDrawer,
  PaModal,
  PaTooltip,
  PaBadge,
  PaInlineMessage,
  PaLoading,
  PaEmptyState,
  PaProgress,
  PaTable,
  PaAccordion,
  PaPagination,
  PaSlider,
  PaRangeSlider,
  PaActionButton,
  PaActionButtonGroup,
  PaActionGroup,
  PaButtonDropdown,
  PaCheckboxGroup,
  PaInputGroup,
  PaCurrencyInput,
  PaDatePicker,
  PaPhoneNumberInputGroup,
  PaToggleInputGroup,
  PaOptionalGroup,
  PaHeroHeader,
  PaHeroIcon,
  PaHeroSubheader,
  PaHeroSubheaderGroup,
  PaFormDivider,
  PaPageDivider,
  PaTextContainer,
  PaTextDivider,
  PaSlottedLayout,
  PaSlottedLayoutHeader,
  PaCircle,
  PaColorPicker,
  PaDivider,
  PaIcon,
  PaNavButton,
  PaNavButtonGroup,
  PaSheet,
  PaSquare,
  PaToggle
} from '../components'

export function useComponentRegistry() {
  const componentMap: Record<string, any> = {
    'pabutton': PaButton,
    'painput': PaInput,
    'pacheckbox': PaCheckbox,
    'paradio': PaRadio,
    'paradiobuttongroup': PaRadioButtonGroup,
    'paswitch': PaSwitch,
    'paselect': PaSelect,
    'patextarea': PaTextarea,
    'paautocomplete': PaAutocomplete,
    'patimepicker': PaTimePicker,
    'pafileuploader': PaFileUploader,
    'paform': PaForm,
    'pacard': PaCard,
    'paheader': PaHeader,
    'palistitem': PaListItem,
    'papagelayout': PaPageLayout,
    'pacontentseparator': PaContentSeparator,
    'pacontainer': PaContainer,
    'paformcontainer': PaFormContainer,
    'pasectioncontainer': PaSectionContainer,
    'padropdown': PaDropdown,
    'pasegmentedcontrol': PaSegmentedControl,
    'patogglesegmentation': PaToggleSegmentation,
    'patogglechip': PaToggleChip,
    'pakebabmenu': PaKebabMenu,
    'patabs': PaTabs,
    'pabreadcrumbs': PaBreadcrumbs,
    'pastepper': PaStepper,
    'padrawer': PaDrawer,
    'pamodal': PaModal,
    'patooltip': PaTooltip,
    'pabadge': PaBadge,
    'painlinemessage': PaInlineMessage,
    'paloading': PaLoading,
    'paemptystate': PaEmptyState,
    'paprogress': PaProgress,
    'patable': PaTable,
    'paaccordion': PaAccordion,
    'papagination': PaPagination,
    'paslider': PaSlider,
    'parangeslider': PaRangeSlider,
    'paactionbutton': PaActionButton,
    'paactionbuttongroup': PaActionButtonGroup,
    'paactiongroup': PaActionGroup,
    'pabuttondropdown': PaButtonDropdown,
    'pacheckboxgroup': PaCheckboxGroup,
    'painputgroup': PaInputGroup,
    'pacurrencyinput': PaCurrencyInput,
    'padatepicker': PaDatePicker,
    'paphonenumberinputgroup': PaPhoneNumberInputGroup,
    'patoggleinputgroup': PaToggleInputGroup,
    'paoptionalgroup': PaOptionalGroup,
    'paheroheader': PaHeroHeader,
    'paheroicon': PaHeroIcon,
    'paherosubheader': PaHeroSubheader,
    'paherosubheadergroup': PaHeroSubheaderGroup,
    'paformdivider': PaFormDivider,
    'papagedivider': PaPageDivider,
    'patextcontainer': PaTextContainer,
    'patextdivider': PaTextDivider,
    'paslottedlayout': PaSlottedLayout,
    'paslottedlayoutheader': PaSlottedLayoutHeader,
    'pacircle': PaCircle,
    'pacolorpicker': PaColorPicker,
    'padivider': PaDivider,
    'paicon': PaIcon,
    'panavbutton': PaNavButton,
    'panavbuttongroup': PaNavButtonGroup,
    'pasheet': PaSheet,
    'pasquare': PaSquare,
    'patoggle': PaToggle
  }

  const getComponent = (componentId: string) => {
    return componentMap[componentId] || null
  }

  return {
    getComponent
  }
}

